FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o order-service ./services/order-service/cmd/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/order-service .
COPY --from=builder /app/services/order-service/config/config.yaml ./config/config.yaml

EXPOSE 8083
CMD ["./order-service"]