FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o restaurant-service ./services/restaurant-service/cmd/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/restaurant-service .
COPY --from=builder /app/services/restaurant-service/config/config.yaml ./config/config.yaml

EXPOSE 8082
CMD ["./restaurant-service"]
