// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/restaurant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *GetRestaurantRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       uint32                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	IsOpen        bool                   `protobuf:"varint,7,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantResponse) Reset() {
	*x = GetRestaurantResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantResponse) ProtoMessage() {}

func (x *GetRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *GetRestaurantResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRestaurantResponse) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetRestaurantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRestaurantResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRestaurantResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetRestaurantResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetRestaurantResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type GetMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemRequest) Reset() {
	*x = GetMenuItemRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRequest) ProtoMessage() {}

func (x *GetMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *GetMenuItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  uint32                 `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,6,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemResponse) Reset() {
	*x = GetMenuItemResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemResponse) ProtoMessage() {}

func (x *GetMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuItemResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMenuItemResponse) GetRestaurantId() uint32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *GetMenuItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMenuItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetMenuItemResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetMenuItemResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type ValidateMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemIds   []uint32               `protobuf:"varint,1,rep,packed,name=menu_item_ids,json=menuItemIds,proto3" json:"menu_item_ids,omitempty"`
	RestaurantId  uint32                 `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMenuItemsRequest) Reset() {
	*x = ValidateMenuItemsRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMenuItemsRequest) ProtoMessage() {}

func (x *ValidateMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*ValidateMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateMenuItemsRequest) GetMenuItemIds() []uint32 {
	if x != nil {
		return x.MenuItemIds
	}
	return nil
}

func (x *ValidateMenuItemsRequest) GetRestaurantId() uint32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type MenuItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,4,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemInfo) Reset() {
	*x = MenuItemInfo{}
	mi := &file_proto_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemInfo) ProtoMessage() {}

func (x *MenuItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemInfo.ProtoReflect.Descriptor instead.
func (*MenuItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *MenuItemInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItemInfo) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type ValidateMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Items         []*MenuItemInfo        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMenuItemsResponse) Reset() {
	*x = ValidateMenuItemsResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMenuItemsResponse) ProtoMessage() {}

func (x *ValidateMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*ValidateMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateMenuItemsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateMenuItemsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateMenuItemsResponse) GetItems() []*MenuItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_restaurant_proto protoreflect.FileDescriptor

const file_proto_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x16proto/restaurant.proto\x12\n" +
	"restaurant\"&\n" +
	"\x14GetRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xc1\x01\n" +
	"\x15GetRestaurantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\rR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x17\n" +
	"\ais_open\x18\a \x01(\bR\x06isOpen\"$\n" +
	"\x12GetMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xb3\x01\n" +
	"\x13GetMenuItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\rR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12!\n" +
	"\fis_available\x18\x06 \x01(\bR\visAvailable\"c\n" +
	"\x18ValidateMenuItemsRequest\x12\"\n" +
	"\rmenu_item_ids\x18\x01 \x03(\rR\vmenuItemIds\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\rR\frestaurantId\"k\n" +
	"\fMenuItemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12!\n" +
	"\fis_available\x18\x04 \x01(\bR\visAvailable\"w\n" +
	"\x19ValidateMenuItemsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.restaurant.MenuItemInfoR\x05items2\x9b\x02\n" +
	"\x11RestaurantService\x12T\n" +
	"\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a!.restaurant.GetRestaurantResponse\x12N\n" +
	"\vGetMenuItem\x12\x1e.restaurant.GetMenuItemRequest\x1a\x1f.restaurant.GetMenuItemResponse\x12`\n" +
	"\x11ValidateMenuItems\x12$.restaurant.ValidateMenuItemsRequest\x1a%.restaurant.ValidateMenuItemsResponseB3Z1github.com/448267450/food-delivery-platform/protob\x06proto3"

var (
	file_proto_restaurant_proto_rawDescOnce sync.Once
	file_proto_restaurant_proto_rawDescData []byte
)

func file_proto_restaurant_proto_rawDescGZIP() []byte {
	file_proto_restaurant_proto_rawDescOnce.Do(func() {
		file_proto_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_restaurant_proto_rawDesc), len(file_proto_restaurant_proto_rawDesc)))
	})
	return file_proto_restaurant_proto_rawDescData
}

var file_proto_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_restaurant_proto_goTypes = []any{
	(*GetRestaurantRequest)(nil),      // 0: restaurant.GetRestaurantRequest
	(*GetRestaurantResponse)(nil),     // 1: restaurant.GetRestaurantResponse
	(*GetMenuItemRequest)(nil),        // 2: restaurant.GetMenuItemRequest
	(*GetMenuItemResponse)(nil),       // 3: restaurant.GetMenuItemResponse
	(*ValidateMenuItemsRequest)(nil),  // 4: restaurant.ValidateMenuItemsRequest
	(*MenuItemInfo)(nil),              // 5: restaurant.MenuItemInfo
	(*ValidateMenuItemsResponse)(nil), // 6: restaurant.ValidateMenuItemsResponse
}
var file_proto_restaurant_proto_depIdxs = []int32{
	5, // 0: restaurant.ValidateMenuItemsResponse.items:type_name -> restaurant.MenuItemInfo
	0, // 1: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.GetRestaurantRequest
	2, // 2: restaurant.RestaurantService.GetMenuItem:input_type -> restaurant.GetMenuItemRequest
	4, // 3: restaurant.RestaurantService.ValidateMenuItems:input_type -> restaurant.ValidateMenuItemsRequest
	1, // 4: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.GetRestaurantResponse
	3, // 5: restaurant.RestaurantService.GetMenuItem:output_type -> restaurant.GetMenuItemResponse
	6, // 6: restaurant.RestaurantService.ValidateMenuItems:output_type -> restaurant.ValidateMenuItemsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_restaurant_proto_init() }
func file_proto_restaurant_proto_init() {
	if File_proto_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_restaurant_proto_rawDesc), len(file_proto_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_restaurant_proto_goTypes,
		DependencyIndexes: file_proto_restaurant_proto_depIdxs,
		MessageInfos:      file_proto_restaurant_proto_msgTypes,
	}.Build()
	File_proto_restaurant_proto = out.File
	file_proto_restaurant_proto_goTypes = nil
	file_proto_restaurant_proto_depIdxs = nil
}
